/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.administrador.GUI;


import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class AgregarEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form AgregarEmpleado
     */
    public AgregarEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        jTextCedula = new javax.swing.JTextField();
        jTextContrasena = new javax.swing.JTextField();
        jTextConfirmada = new javax.swing.JTextField();
        jButtonAgregarEmpleado = new javax.swing.JButton();
        jButtonInicio = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTitulo.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabelTitulo.setText("Agregar Empleado");

        jLabel1.setText("Sede a la que se agregara el Empleado:");

        jLabel2.setText("de la entidad con Nit :");

        jTextSede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextSedeActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre del Empleado:");

        jLabel4.setText("Cédula:");

        jLabel5.setText("Contraseña:");

        jLabel6.setText("Confirmar Contraseña:");

        jTextCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCedulaActionPerformed(evt);
            }
        });

        jButtonAgregarEmpleado.setText("Agregar");
        jButtonAgregarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarEmpleadoActionPerformed(evt);
            }
        });

        jButtonInicio.setText("Inicio");
        jButtonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInicioActionPerformed(evt);
            }
        });

        jLabel8.setText("Código de la Sede:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextNombre)
                                    .addComponent(jTextCedula)
                                    .addComponent(jTextContrasena)
                                    .addComponent(jTextConfirmada, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                                    .addComponent(jTextNit)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jTextSede, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(34, 34, 34)
                        .addComponent(jTextNombreSede, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jButtonInicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAgregarEmpleado)
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTitulo)
                .addGap(132, 132, 132))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabelTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jTextNombreSede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jTextSede, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTextNit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextConfirmada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAgregarEmpleado)
                    .addComponent(jButtonInicio))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextSedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextSedeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextSedeActionPerformed

    private void jTextCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCedulaActionPerformed

    private void jButtonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInicioActionPerformed
        // TODO add your handling code here:
        
        MenuAdmin menu = new MenuAdmin();
        menu.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButtonInicioActionPerformed

    private void jButtonAgregarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarEmpleadoActionPerformed
        // TODO add your handling code here:
        
        String nombreSede= this.jTextNombreSede.getText();
        boolean[] verificar = new boolean[6];
        String Nit = this.jTextNit.getText();
        verificar[0]= this.jTextNit.getText().isEmpty();
        String sede = this.jTextSede.getText();
        verificar[1] = this.jTextSede.getText().isEmpty();
        String cedula = this.jTextCedula.getText();
        verificar[2] =  this.jTextCedula.getText().isEmpty();
        String nombre = this.jTextNombre.getText();
        verificar[3] = this.jTextNombre.getText().isEmpty();
        String contrasena = this.jTextContrasena.getText();
        verificar[4]=this.jTextContrasena.getText().isEmpty();
        String confirmar = this.jTextConfirmada.getText();
        verificar[5]= this.jTextConfirmada.getText().isEmpty();
        
        
        if(!verificar[0] && !verificar[1] && !verificar[2] && !verificar[3] && !verificar[4] && !verificar[5]  ){
            
            if(contrasena.equals(confirmar)){
                
                if(agregarEmpleado(cedula,nombre,contrasena,sede)){
                
                    JOptionPane.showMessageDialog(null ,"El empleado ha sido agregado a la sede"+ nombreSede );
                
                 int respuesta = JOptionPane.showConfirmDialog(null ,"Desea Agregar otro empleado a la sede "+ nombreSede,"Agregar Empleado", JOptionPane.YES_NO_OPTION );
                 if(respuesta==JOptionPane.YES_OPTION){
                       
                     AgregarEmpleado nuevo = new AgregarEmpleado();

                     nuevo.setVisible(true);
                     nuevo.jTextNit.setText(Nit);
                     nuevo.jTextNombreSede.setText(nombreSede);
                     nuevo.jTextSede.setText(String.valueOf(sede));

                        }else{
                     
                     //int respuesta1 = JOptionPane.showConfirmDialog(null ,"Desea Agregar un receptor a la sede: "+ nombreSede,"Agregar Receptor", JOptionPane.YES_NO_OPTION );
                     int respuesta1 = JOptionPane.showConfirmDialog(null ,"Desea Agregar los servicios a la sede: "+ nombreSede,"Agregar Servicios", JOptionPane.YES_NO_OPTION );
                     if(respuesta1==JOptionPane.YES_OPTION){
                         AgregarServicios nuevo = new AgregarServicios();
                         nuevo.setVisible(true);
                         nuevo.jTextNombreSede.setText(nombreSede);
                         nuevo.jTextCodigoSede.setText(sede);
                         this.setVisible(false);
             /*
                            AgregarReceptor nuevo = new AgregarReceptor();
                            nuevo.setVisible(true);
                            nuevo.jTextNombreSede.setText(nombreSede);
                            nuevo.jTextSede.setText(sede);
                            nuevo.setVisible(true);
             */               
                            
                     }else{
                     MenuAdmin menu = new MenuAdmin();
                     menu.setVisible(true);
                     this.setVisible(false);
                     
                     }

                        }
                
                
                }else{
                
                    JOptionPane.showMessageDialog(null ,"Error. El empleado con la cedula ingresada ya existe" ,"Problema proceso",JOptionPane.ERROR_MESSAGE);
                }
                
            }else{
            JOptionPane.showMessageDialog(null ,"Por favor verifique que la contraseña y la confirmacion sean iguales" );
            }
        
        }else{
        JOptionPane.showMessageDialog(null ,"Por favor verifique que todos los campos estan llenos" );
        }
      
    }//GEN-LAST:event_jButtonAgregarEmpleadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarEmpleado;
    private javax.swing.JButton jButtonInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JTextField jTextCedula;
    private javax.swing.JTextField jTextConfirmada;
    private javax.swing.JTextField jTextContrasena;
    public final javax.swing.JTextField jTextNit = new javax.swing.JTextField();
    private javax.swing.JTextField jTextNombre;
    public final javax.swing.JTextField jTextNombreSede = new javax.swing.JTextField();
    public final javax.swing.JTextField jTextSede = new javax.swing.JTextField();
    // End of variables declaration//GEN-END:variables

    private static boolean agregarEmpleado(java.lang.String cedula, java.lang.String nombre, java.lang.String contrasena, java.lang.String sede) {
        com.esperapp.ws.AsignarTurnos_Service service = new com.esperapp.ws.AsignarTurnos_Service();
        com.esperapp.ws.AsignarTurnos port = service.getAsignarTurnosPort();
        return port.agregarEmpleado(cedula, nombre, contrasena, sede);
    }
  

    
    
    
    

  
}
