/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.administrador.GUI;

import com.esperapp.ws.Servicio;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Rafael
 */
public class AgregarServicios extends javax.swing.JFrame {

    /**
     * Creates new form AgregarServicios
     */
    public AgregarServicios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextServicio = new javax.swing.JTextField();
        jButtonAgregarServicio = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonInicio = new javax.swing.JButton();
        jButtonAgregarReceptores = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxServiciosExistentes = new javax.swing.JComboBox<>();
        jButtonEliminarServicio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Agregar Servicios");

        jLabel2.setText("Servicio:");

        jTextServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextServicioActionPerformed(evt);
            }
        });

        jButtonAgregarServicio.setText("Agregar");
        jButtonAgregarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarServicioActionPerformed(evt);
            }
        });

        jLabel3.setText("Sede:");

        jLabel4.setText("Codigo:");

        jButtonInicio.setText("Inicio");

        jButtonAgregarReceptores.setText("Siguente");
        jButtonAgregarReceptores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarReceptoresActionPerformed(evt);
            }
        });

        jLabel5.setText("Servicios Existentes:");

        jButtonEliminarServicio.setText("Eliminar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextCodigoSede, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextNombreSede, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonInicio)
                        .addGap(78, 78, 78)
                        .addComponent(jButtonAgregarReceptores))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jComboBoxServiciosExistentes, javax.swing.GroupLayout.Alignment.LEADING, 0, 188, Short.MAX_VALUE)
                            .addComponent(jTextServicio, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAgregarServicio)
                            .addComponent(jButtonEliminarServicio))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextNombreSede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextCodigoSede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAgregarServicio))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxServiciosExistentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEliminarServicio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonInicio)
                    .addComponent(jButtonAgregarReceptores))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextServicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextServicioActionPerformed

    private void jButtonAgregarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarServicioActionPerformed
        // TODO add your handling code here:
        
        String nombreSede= this.jTextNombreSede.getText();
        String sedeId = this.jTextCodigoSede.getText();
        String tipoServicio = this.jTextServicio.getText();
        boolean[] verificar = new boolean[3];
        verificar[0]= this.jTextCodigoSede.getText().isEmpty();
        verificar[1]= this.jTextServicio.getText().isEmpty();
        List<Servicio> serviciosActuales;
       
       
        
        if(!verificar[0] && !verificar[1]){
            
           if(agregarServicio(sedeId,tipoServicio )){
           
               
               JOptionPane.showMessageDialog(null ,"se agrego el Servicio correctamente" );
              serviciosActuales = buscarServiciosSede(sedeId);
              Iterator<Servicio> It = serviciosActuales.iterator();
               for (int i =this.jComboBoxServiciosExistentes.getItemCount() - 1; i >= 0; i--) {
                   this.jComboBoxServiciosExistentes.removeItemAt(i);
               }
               while(It.hasNext()){
              
                  this.jComboBoxServiciosExistentes.addItem(It.next().getTipo());
              }
     
              
 
           }else{
           
               JOptionPane.showMessageDialog(null ," No se pudo agregar el Servicio " );
           }
            
        
        
        }else{
        
             JOptionPane.showMessageDialog(null ,"Por favor verifique que todos los campos estan llenos" );
        
        }
    }//GEN-LAST:event_jButtonAgregarServicioActionPerformed

    private void jButtonAgregarReceptoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarReceptoresActionPerformed
        // TODO add your handling code here:
         String nombreSede= this.jTextNombreSede.getText();
        String sedeId = this.jTextCodigoSede.getText();
        int respuesta1 = JOptionPane.showConfirmDialog(null ,"Desea Agregar un receptor a la sede: "+ nombreSede,"Agregar Receptor", JOptionPane.YES_NO_OPTION );
                     if(respuesta1==JOptionPane.YES_OPTION){
                     
                     AgregarReceptor nuevo = new AgregarReceptor();
                          
                     nuevo.setVisible(true);
                            nuevo.jTextNombreSede.setText(nombreSede);
                            nuevo.jTextSede.setText(sedeId);
                            
                            this.setVisible(false);
                     
                     }
    }//GEN-LAST:event_jButtonAgregarReceptoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarServicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarServicios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarReceptores;
    private javax.swing.JButton jButtonAgregarServicio;
    private javax.swing.JButton jButtonEliminarServicio;
    private javax.swing.JButton jButtonInicio;
    private javax.swing.JComboBox<String> jComboBoxServiciosExistentes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public final javax.swing.JTextField jTextCodigoSede = new javax.swing.JTextField();
    public final javax.swing.JTextField jTextNombreSede = new javax.swing.JTextField();
    private javax.swing.JTextField jTextServicio;
    // End of variables declaration//GEN-END:variables

   

    private static java.util.List<com.esperapp.ws.Servicio> buscarServiciosSede(java.lang.String codigoSede) {
        com.esperapp.ws.AsignarTurnos_Service service = new com.esperapp.ws.AsignarTurnos_Service();
        com.esperapp.ws.AsignarTurnos port = service.getAsignarTurnosPort();
        return port.buscarServiciosSede(codigoSede);
    }

    private static boolean agregarServicio(java.lang.String codigoSede, java.lang.String servicio) {
        com.esperapp.ws.AsignarTurnos_Service service = new com.esperapp.ws.AsignarTurnos_Service();
        com.esperapp.ws.AsignarTurnos port = service.getAsignarTurnosPort();
        return port.agregarServicio(codigoSede, servicio);
    }



   





}
