/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.administrador.GUI;

import com.esperapp.ws.Entidad;
import com.esperapp.ws.Sede;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class BuscarSede extends javax.swing.JFrame {
private List<Sede> listaSedes;
    /**
     * Creates new form BuscarSede
     */
    public BuscarSede() {
        initComponents();
        llenarItems();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextBCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboSedes = new javax.swing.JComboBox();
        jButtonBuscarSede = new javax.swing.JButton();
        jButtonSelect = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextEntidad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextSedeId = new javax.swing.JTextField();
        jTextNombre = new javax.swing.JTextField();
        jTextNombreContacto = new javax.swing.JTextField();
        jTextTelefono = new javax.swing.JTextField();
        jTextCorreo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        TextDireccion = new javax.swing.JTextField();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Buscar Sede");

        jLabel2.setText("Ingrese el Código de la Sede :");

        jLabel3.setText("o seleccione una Sede :");

        jButtonBuscarSede.setText("Buscar");
        jButtonBuscarSede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarSedeActionPerformed(evt);
            }
        });

        jButtonSelect.setText("Select");
        jButtonSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelectActionPerformed(evt);
            }
        });

        jLabel4.setText("Pertenece a la Entidad con NIT:");

        jLabel5.setText("ID-Sede:");

        jLabel6.setText("Nombre:");

        jLabel7.setText("Nombre Contacto:");

        jLabel8.setText("Teléfono:");

        jLabel9.setText("Correo:");

        jButton1.setText("Inicio");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Agregar Empleado");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Agregar Servicios");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel10.setText("Direccion:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(176, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(56, 56, 56)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jTextTelefono, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextNombreContacto, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextSedeId, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextBCodigo, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jComboSedes, javax.swing.GroupLayout.Alignment.LEADING, 0, 162, Short.MAX_VALUE)
                                            .addComponent(jTextEntidad, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextCorreo)
                                            .addComponent(TextDireccion))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButtonBuscarSede)
                                            .addComponent(jButtonSelect))))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextBCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarSede))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboSedes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSelect))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextSedeId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextNombreContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(TextDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton3)
                    .addComponent(jButton1)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarSedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarSedeActionPerformed
        // TODO add your handling code here:
        List<String> sede;
        String codigo= this.jTextBCodigo.getText();
       
        
        if (!this.jTextBCodigo.getText().isEmpty()){
            
            sede =  buscarSedeCodigo(codigo);
            
            if(!sede.isEmpty()){
            
            Iterator<String> It= sede.iterator();
            this.jTextEntidad.setText(It.next());
            this.jTextSedeId.setText(It.next());
            this.jTextNombre.setText(It.next());
            this.jTextNombreContacto.setText(It.next());
            this.jTextTelefono.setText(It.next());
            this.jTextCorreo.setText(It.next());
            this.TextDireccion.setText(It.next());
            }else{
                JOptionPane. showMessageDialog(null ,"codigo no valido" );
            }

            
        
        
        
        }else{
            JOptionPane. showMessageDialog(null ,"Ingrese un Nit a buscar" );
        }
        
    }//GEN-LAST:event_jButtonBuscarSedeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          MenuAdmin menu = new MenuAdmin();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectActionPerformed
        // TODO add your handling code here:
       int index = this.jComboSedes.getSelectedIndex();
      
       Iterator<Sede> It = listaSedes.iterator();
       Sede sede = null;     
       for(int i=0; i<=index ; i++){
           sede = It.next();
           
       }
       
       if(sede!=null){ 
           
          // Entidad entidad = sede.getEntidad();
       //this.jTextEntidad.setText(entidad.getIDNit());
        
       this.jTextSedeId.setText(sede.getIDSede());
       this.jTextNombre.setText(sede.getNombre());
       this.jTextNombreContacto.setText(sede.getNombreContacto());
       this.jTextTelefono.setText(sede.getTelefonoContacto());
       this.jTextCorreo.setText(sede.getCorreoContacto());
       this.TextDireccion.setText(sede.getDireccion());
       }else{
           JOptionPane.showMessageDialog(null ,"Error. No hay nada en el seleccionador" ,"Problema proceso",JOptionPane.ERROR_MESSAGE);
       }
       

                          
    }//GEN-LAST:event_jButtonSelectActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         
        String nit = this.jTextEntidad.getText();
        String Nombre = this.jTextNombre.getText();
        String codigoSede = this.jTextSedeId.getText();
        
        if(!this.jTextEntidad.getText().isEmpty() && !this.jTextNombre.getText().isEmpty() && !this.jTextSedeId.getText().isEmpty()){
        
        AgregarEmpleado nuevo = new AgregarEmpleado();

                     nuevo.setVisible(true);
                     nuevo.jTextNit.setText(nit);
                     nuevo.jTextNombreSede.setText(Nombre);
                     nuevo.jTextSede.setText(String.valueOf(codigoSede));
                     
        }else{
         JOptionPane. showMessageDialog(null ,"Seleccione una sede a la cual agregar un empleado" );
        }            
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here: 
        
        String Nombre = this.jTextNombre.getText();
        String codigoSede = this.jTextSedeId.getText();
        
        if(!this.jTextNombre.getText().isEmpty() && !this.jTextSedeId.getText().isEmpty()){
            AgregarServicios nuevo = new AgregarServicios();
                            nuevo.setVisible(true);
                            nuevo.jTextNombreSede.setText(Nombre);
                            nuevo.jTextCodigoSede.setText(codigoSede);

                            this.setVisible(false);
        } else{
         JOptionPane. showMessageDialog(null ,"Seleccione una sede a la cual agregar un Receptor" );
        }                  
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarSede.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarSede.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarSede.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarSede.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarSede().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextDireccion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonBuscarSede;
    private javax.swing.JButton jButtonSelect;
    private javax.swing.JComboBox jComboSedes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextBCodigo;
    private javax.swing.JTextField jTextCorreo;
    private javax.swing.JTextField jTextEntidad;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextNombreContacto;
    private javax.swing.JTextField jTextSedeId;
    private javax.swing.JTextField jTextTelefono;
    // End of variables declaration//GEN-END:variables

   

    private void llenarItems() {
        //To change body of generated methods, choose Tools | Templates.
        
        listaSedes = buscarSedesClase();
        
        Iterator<Sede> It= listaSedes.iterator();
        
        
        while(It.hasNext()){
            
            this.jComboSedes.addItem(It.next().getNombre());
        
        
        }
    }
    /**
     * buscarSedes
     * @return list
     * busca todas las sedes de una entidad determinada y retorna una lista con ellas
     */
    private static java.util.List<com.esperapp.ws.Sede> buscarSedesClase() {
        com.esperapp.ws.AsignarTurnos_Service service = new com.esperapp.ws.AsignarTurnos_Service();
        com.esperapp.ws.AsignarTurnos port = service.getAsignarTurnosPort();
        return port.buscarSedesClase();
    }

    private static java.util.List<java.lang.String> buscarSedeCodigo(java.lang.String cod) {
        com.esperapp.ws.AsignarTurnos_Service service = new com.esperapp.ws.AsignarTurnos_Service();
        com.esperapp.ws.AsignarTurnos port = service.getAsignarTurnosPort();
        return port.buscarSedeCodigo(cod);
    }

   
}
